/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:b267601b-538e-4645-9dc2-18672fc6b349",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_y7C8sHEjn",
    "aws_user_pools_web_client_id": "6d7c9r2gmbnsqg3idjc431faj",
    "oauth": {}
};


export default awsmobile;
